<a href="https://colab.research.google.com/github/juizykad-netizen/AIML_PYTHON/blob/main/Assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Upload Dataset to Colab

In [1]:
from google.colab import files
uploaded = files.upload()

Saving test_2umaH9m.csv to test_2umaH9m (1).csv
Saving train_LZdllcl.csv to train_LZdllcl (1).csv

2. Load the Data

In [5]:
import pandas as pd

train = pd.read_csv("/content/train_LZdllcl.csv")
test = pd.read_csv("/content/test_2umaH9m.csv")

train.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

3. Understand the data.

In [6]:
train.info()
train.describe()
train.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           54808 non-null  int64
 1   department            54808 non-null  object
 2   region                54808 non-null  object
 3   education             52399 non-null  object
 4   gender                54808 non-null  object
 5   recruitment_channel   54808 non-null  object
 6   no_of_trainings       54808 non-null  int64
 7   age                   54808 non-null  int64
 8   previous_year_rating  50684 non-null  float64
 9   length_of_service     54808 non-null  int64
 10  KPIs_met >80%         54808 non-null  int64
 11  awards_won?           54808 non-null  int64
 12  avg_training_score    54808 non-null  int64
 13  is_promoted           54808 non-null  int64
dtypes: float64(1), int64(8), object(5)
memory usage: 5.9+ MB

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

4. Data Cleaning

Handle missing values.

In [7]:
train['education'].fillna("Unknown", inplace=True)
train['previous_year_rating'].fillna(train['previous_year_rating'].median(), inplace=True)

/tmp/ipykernel_975/1980079965.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['education'].fillna("Unknown", inplace=True)
/tmp/ipykernel_975/1980079965.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['previous_year_rating'].fillna(train['previous_year_rating'].median(), inplace=True)

5. Convert Text Data to Numbers

Machine learning models need numerical input.

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

train['gender'] = le.fit_transform(train['gender'])
train['department'] = le.fit_transform(train['department'])

6. Define Target Variable

Target column = is_promoted

In [11]:
X = train.drop(['employee_id','is_promoted'], axis=1)
y = train['is_promoted']

7. Split Training Data

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [17]:
X_train.dtypes

department                int64
region                   object
education                object
gender                    int64
recruitment_channel      object
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
dtype: object

Fixing Errors before training the model

Encode the Object Columns

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X_train['region'] = le.fit_transform(X_train['region'])
X_train['education'] = le.fit_transform(X_train['education'])
X_train['recruitment_channel'] = le.fit_transform(X_train['recruitment_channel'])

apply to validation set:

In [19]:
X_val['region'] = le.fit_transform(X_val['region'])
X_val['education'] = le.fit_transform(X_val['education'])
X_val['recruitment_channel'] = le.fit_transform(X_val['recruitment_channel'])

2.Check Missing Values (Very Important)

In [20]:
X_train.isnull().sum()

department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in ['region','education','recruitment_channel']:
    X_train[col] = le.fit_transform(X_train[col])
    X_val[col] = le.transform(X_val[col])

8. Train Machine Learning Model

In [23]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

9. Evaluate Model

In [24]:
from sklearn.metrics import f1_score

pred = model.predict(X_val)

f1_score(y_val, pred)

0.43357783211083945

Important Step Before Prediction

You must apply the same encoding to the test dataset.

Encode test data

Run this before prediction:

In [27]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in ['region','education','recruitment_channel']:
    test[col] = le.fit_transform(test[col])

If department was also text in test, include it too:

In [28]:
for col in ['department','region','education','recruitment_channel']:
    test[col] = le.fit_transform(test[col])

Check Test Data Types

In [31]:
test.dtypes

employee_id               int64
department                int64
region                    int64
education                 int64
gender                   object
recruitment_channel       int64
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
dtype: object

Fix the Gender Column

Convert gender to numbers in the test dataset.

In [32]:
test['gender'] = test['gender'].map({'m':0, 'f':1})

In [33]:
test.dtypes

employee_id               int64
department                int64
region                    int64
education                 int64
gender                    int64
recruitment_channel       int64
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
dtype: object

10. Predict Test Data

In [34]:
test_X = test.drop('employee_id', axis=1)

test_pred = model.predict(test_X)

11. Create Submission File

In [36]:
submission = pd.DataFrame({
    "employee_id": test["employee_id"],
    "is_promoted": test_pred
})

submission.to_csv("submission.csv", index=False)

12. Upload Prediction